CC = gcc
CFLAGS = -Wall -Werror

all: my-cat my-grep my-zip my-unzip

my-cat: my-cat.c
	$(CC) $(CFLAGS) -o my-cat my-cat.c

my-grep: my-grep.c
	$(CC) $(CFLAGS) -o my-grep my-grep.c

my-zip: my-zip.c
	$(CC) $(CFLAGS) -o my-zip my-zip.c

my-unzip: my-unzip.c
	$(CC) $(CFLAGS) -o my-unzip my-unzip.c